version: '3.1'
services:
  app:
    container_name: awarean-payroll-loans-api
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - 5001:443
      - 5000:80
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=app_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  db:
    image: postgres:latest
    ports: 
      - 5432:5432
    restart: always
    networks:
      - app-network
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=appdb
    volumes:
      - dbvolume:/var/lib/postgresql/data
      - ./.dbscripts/create-databasel.sql :/docker-entrypoint-init.d/create-database.sql
  
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app-network

volumes:
  dbvolume:

networks:
  app-network:
    driver: bridge